name: Build Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Позволяет запускать сборку вручную

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x gradlew
      
      - name: Setup Forge workspace
        run: ./gradlew --no-daemon eclipse
        continue-on-error: true
      
      - name: Build mod
        run: ./gradlew --no-daemon build
      
      - name: Upload built mod
        uses: actions/upload-artifact@v3
        with:
          name: ghostadmin-mod
          path: build/libs/*.jar
